WITH source AS (SELECT 
Id as diagnostics_id,
Name as diagnostics_name,
Grade__c as assessment_grade,
A_Q_1_1__c as a_q1,
A_Q_1_2__c as a_q2,	
A_Q_1_3__c as a_q3,	
A_Q_1_4__c as a_q4,	
A_Q_1_5__c as a_q5,	
A_Q_1_6__c as a_q6,	
A_Q_1_7__c as a_q7,	
A_Q_1_8__c as a_q8,	
A_Q_1_9__c as a_q9,	
A_Q_1_10__c as a_q10,
A_Q_1_1_Marks__c as a_q1_marks,	
A_Q_1_2_Marks__c as a_q2_marks,	
A_Q_1_3_Marks__c as a_q3_marks,	
A_Q_1_4_Marks__c as a_q4_marks,	
A_Q_1_5_Marks__c as a_q5_marks,	
A_Q_1_6_Marks__c as a_q6_marks,	
A_Q_1_7_Marks__c as a_q7_marks,	
A_Q_1_8_Marks__c as a_q8_marks,	
A_Q_1_9_Marks__c as a_q9_marks,
A_Q_1_10_Marks__c as a_q10_marks,
B_Q_1_1__c as b_q1,	
B_Q_1_2__c as b_q2,	
B_Q_1_3__c as b_q3,	
B_Q_1_4__c as b_q4,	
B_Q_1_5__c as b_q5,	
B_Q_1_6__c as b_q6,	
B_Q_1_7__c as b_q7,	
B_Q_1_8__c as b_q8,	
B_Q_1_9__c as b_q9,	
B_Q_1_10__c as b_q10,
B_Q_1_1_Marks__c as b_q1_marks,	
B_Q_1_2_Marks__c as b_q2_marks,	
B_Q_1_3_Marks__c as b_q3_maks,	
B_Q_1_4_Marks__c as b_q4_marks,	
B_Q_1_5_Marks__c as b_q5_marks,	
B_Q_1_6_Marks__c as b_q6_marks,	
B_Q_1_7_Marks__c as b_q7_marks,	
B_Q_1_8_Marks__c as b_q8_marks,	
B_Q_1_9_Marks__c as b_q9_marks,
B_Q_1_10_Marks__c as b_q10_marks,
Barcode__c as assessment_barcode,	
Student__c as assessment_student_id,	
Batch_Id__c as assessment_batch_id,	
CreatedById as created_by_id,	
CreatedDate as created_by_date,	
Form_Name__c as form_name,	
RecordTypeId as record_type_id,	
Error_Status__c	error_status,
Academic_Year__c as assessment_academic_year,	
Form_Language__c as form_language,	
LastModifiedDate as last_modified_date,	
Created_from_Form__c as created_from_form,	
Marks_Recalculated__c as marks_recalculated,	
Form_submitted_Set_A__c as form_submitted_set_a,	
Form_submitted_Set_B__c as form_submitted_set_b

 FROM {{ source('salesforce', 'Student_Diagnostic__c') }}
 WHERE IsDeleted = False
 )

SELECT * FROM source