with source as (select Id as diagnostics_id,
name as diagnostics_name,
grade__c as batch_grade,	
barcode__c as student_barcode,
batch_id__c as batch_id,
created_date as created_date,
form_name__c as form_name,	
recordtypeid as record_type_id,	
error_status__c as error_status,	
a_q_1_1_marks__c as a_q1,
a_q_1_2_marks__c as a_q2,	
a_q_1_3_marks__c as a_q3,	
a_q_1_4_marks__c as a_q4,	
a_q_1_5_marks__c as a_q5,	
a_q_1_6_marks__c as a_q6,	
a_q_1_7_marks__c as a_q7,	
a_q_1_8_marks__c as a_q8,	
a_q_1_9_marks__c as a_q9,
a_q_1_10_marks__c as a_q10,
academic_year__c as batch_academic_year,	
b_q_1_1_marks__c as b_q1,	
b_q_1_2_marks__c as b_q2,	
b_q_1_3_marks__c as b_q3,	
b_q_1_4_marks__c as b_q4,	
b_q_1_5_marks__c as b_q5,	
b_q_1_6_marks__c as b_q6,	
b_q_1_7_marks__c as b_q7,	
b_q_1_8_marks__c as b_q8,	
b_q_1_9_marks__c as b_q9,	
b_q_1_10_marks__c as b_q10,
data_clean_up__c as data_clean_up,	
form_language__c as form_language,	
student_linked__c as student_linked,	
marks_recalculation as marks_recalculation,	
created_from_form__c as created_from_form,
form_submitted_set_a__c as form_submitted_set_a,
form_submitted_set_b__c as form_submitted_set_b

 from {{ source('salesforce', 'Stage_') }}
)

select * from source