version: 2
models:
  - name: stg_batches
    # description:
    columns:
      - name: batches_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_cdm1
    # description:
    columns:
      - name: cdm1_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_cdm2
    # description:
    columns:
      - name: cdm2_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_contacts
    # description:
    columns:
      - name: contact_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_recordtypes
    # description:
    columns:
      - name: record_type_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_session_attendance
    # description:
    columns:
      - name: session_attendance_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_sessions
    # description:
    columns:
      - name: sessions_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_cp
    # description:
    columns:
      - name: cp_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_cs
    # description:
    columns:
      - name: cs_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_fp
    # description:
    columns:
      - name: fp_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_accounts
    # description:
    columns:
      - name: account_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null          