version: 2
models:
  - name: stg_batches
    # description:
    columns:
      - name: batches_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_cdm1
    # description:
    columns:
      - name: cdm1_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_cdm2
    # description:
    columns:
      - name: cdm2_id
        description: "The primary key for this table"
        tests:
           - unique
           - not_null
  - name: stg_contacts
    # description:
    columns:
      - name: contact_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_recordtypes
    # description:
    columns:
      - name: record_type_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_session_attendance
    # description:
    columns:
      - name: session_attendance_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_sessions
    # description:
    columns:
      - name: session_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_trainer
    # description:
    columns:
      - name: contact_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
  - name: stg_Session_OMR_Type
    # description:
    columns:
      - name: Session_OMR_Type_id
        description: "The primary key of this table"
        tests:
          - unique
          - not_null
          