with hm_session as (
    select 
        hm_session_name, facilitator_name, hm_session_date, start_time, 
        scheduling_type, rescheduled_counter, session_status, hm_attended, 
        session_lead, session_academic_year, batch_language, school_name, 
        school_taluka, school_district, school_state, school_area, school_partner 
    from {{ ref('dev_int_hm_session') }}
),

pre_program as (
    select 
        pre_start, pre_end, pre_date, pre_name, district_name, 
        school_Nagaland AS pre_school_nagaland, school_Goa AS pre_school_goa, 
        school_Rajasthan as pre_school_rajasthan, school_Mumbai as pre_school_mumbai, 
        school_Thane as pre_school_thane, school_Pune as pre_school_pune, 
        school_Osmanabad as pre_school_osmanabad, school_Yamuna_Nagar as pre_school_yamunanagar, 
        pre_contact_number, Q4_years_in_this_school,
        Q5_organisation_last_year, Q5_option_1, Q5_option_2, Q5_option_3, 
        Q6_heard_of_antarang, Q7_how_did_you_hear as pre_how_did_you_hear, Other_Please_Specify,
        Q8_which_grade, Others_Please_Specify, Q9_which_follow, Q10_which_follow, 
        Q11_think_of_career, Q12_confident_in_career_program,
        Q13_program_activities as pre_program_acitivities, Q14_program_session, 
        Q15_important_secondary_students as pre_important_secondary_students, 
        Q16A_program_inclution_of_all_students,
        Q16C_supporting_students_training_after_school, 
        Q16B__encouraging_students_choosing_careers, Q17_one_thing_for_you_students,
        id AS pre_id, uuid AS pre_uuid, submission_time AS pre_submission_time, school_name as pre_school_name,
        COALESCE(
            school_Yamuna_Nagar, school_Osmanabad, school_Pune, school_Thane, school_Mumbai, school_Rajasthan, school_Goa,
            school_Nagaland, school_name
        ) as school_names
    from {{ source('kobo', 'pre_program_questionaire_form') }}
),

post_program as (
    select 
        post_start, post_end, post_date, post_name, Q3_district_name AS post_district_name, 
        school_name as post_school_name, contact_number as post_contact_number, Q4_how_many_year_in_this_school, 
        Q5_org_our_school_last_year, post_others_please_specify, Q6_heard_of_antarng, 
        Q7_how_did_you_hear as post_how_did_you_hear, Q8_in_which_grade, 
        Q9_which_of_the_following, Q10_answer_that_apply, Q11_thin_for_career_program, 
        Q12_confident, Q13_program_activities as post_program_activities, Q14_program_sessions, 
        Q15_important_secondary_students as post_important_secondary_students, Q16_career_decisions, 
        Q17_materials_that_apply, Q18D_header, Q18A_program_inc_of_all_students, 
        Q18C_supporting_students_raining_after_school, Q18B_encouraging_students_choosing_careers, 
        Q19_leave_school, Q20_thin_for_students, uuid as post_uuid, submission_time as post_submission_time, 
        school_Nagaland as post_school_nagaland, school_Goa as post_school_goa, 
        school_Rajasthan as post_school_rajasthan, school_Mumbai as post_school_mumbai, 
        school_Thane as post_school_thane, school_Pune as post_school_pune, 
        school_Osmanabad as post_school_osmanabad, school_Yamuna_Nagar as post_school_yamunanagar
    from {{ source('kobo', 'post_program_questionaire_form') }}
),

post_questionair as (
    select 
        ques_start, ques_end, ques_date, ques_name, school_name as ques_school_name, 
        Q3_district_name AS ques_district_name, contact_number as ques_contact_number, 
        Q4_heard_of_antarang,Q5_grade, ques_others_please_specify, Q6_which_follow, Q7_role, 
        Q8_materials, Q9_confidence, Q10_secondary_students, Q11D_header, 
        Q11A_program_inc_student, Q11C_support_students_raining_after_school, 
        Q11B_encouraging_students_choosing_careers, Q12_thin_for_students, 
        Q13_big_rom_this_orientation, Q14_nex_after_this_orientation, id as ques_id, 
        uuid as ques_uuid, submission_time as ques_submission_time,
        school_Nagaland as ques_school_nagaland, school_Goa as ques_school_goa, 
        school_Rajasthan as ques_school_rajasthan, school_Mumbai as ques_school_mumbai, 
        school_Thane as ques_school_thane, school_Pune as ques_school_pune, 
        school_Osmanabad as ques_school_osmanabad, school_Yamuna_Nagar as ques_school_yamunanagar
    from {{ source('kobo', 'post_orientation_questionaire_form') }}
),

source_joined as 
(select 
    h.*, 
    pre.*, 
    post.*, 
    ques.*
from hm_session h
left join pre_program pre 
    on h.school_name = pre.school_names
left join post_program post 
    on h.school_name = post.post_school_name
left join post_questionair ques 
    on h.school_name = ques.ques_school_name
),

expand_column as 
(select s.hm_session_name, s.facilitator_name, s.hm_session_date, s.start_time, s.Others_Please_Specify,
  s.scheduling_type, s.rescheduled_counter, s.session_status, s.hm_attended,
  s.session_lead, s.session_academic_year, s.batch_language, s.school_name,
  s.school_taluka, s.school_district, s.school_state, s.school_area, s.school_partner,
  s.pre_start, s.pre_end, s.pre_date, s.pre_name, s.district_name,
  s.pre_school_nagaland, s.pre_school_goa, s.pre_school_rajasthan, s.pre_school_mumbai,
  s.pre_school_thane, s.pre_school_pune, s.pre_school_osmanabad, s.pre_school_yamunanagar,
  s.pre_contact_number, s.Q4_years_in_this_school,
  s.Q5_organisation_last_year, s.Q5_option_1, s.Q5_option_2, s.Q5_option_3,
  s.Q6_heard_of_antarang, s.Other_Please_Specify,
  s.Q11_think_of_career, s.Q12_confident_in_career_program, s.pre_program_acitivities,
  s.Q14_program_session, s.pre_important_secondary_students,
  s.Q16A_program_inclution_of_all_students, s.Q16C_supporting_students_training_after_school,
  s.Q16B__encouraging_students_choosing_careers, s.Q17_one_thing_for_you_students,
  s.pre_id, s.pre_uuid, s.pre_submission_time, s.pre_school_name, s.school_names,
  s.post_start, s.post_end, s.post_date, s.post_name, s.post_district_name,
  s.post_school_name, s.post_contact_number, s.Q4_how_many_year_in_this_school,
  s.Q5_org_our_school_last_year, s.post_others_please_specify, s.Q6_heard_of_antarng,
  s.Q11_thin_for_career_program, s.Q12_confident,
  s.post_program_activities, s.Q14_program_sessions, s.post_important_secondary_students,
  s.Q16_career_decisions, s.Q18D_header,
  s.Q18A_program_inc_of_all_students, s.Q18C_supporting_students_raining_after_school,
  s.Q18B_encouraging_students_choosing_careers, s.Q19_leave_school, s.Q20_thin_for_students,
  s.post_uuid, s.post_submission_time, s.post_school_nagaland, s.post_school_goa,
  s.post_school_rajasthan, s.post_school_mumbai, s.post_school_thane,
  s.post_school_pune, s.post_school_osmanabad, s.post_school_yamunanagar,
  s.ques_start, s.ques_end, s.ques_date, s.ques_name, s.ques_school_name,
  s.ques_district_name, s.ques_contact_number, s.Q4_heard_of_antarang,
  s.ques_others_please_specify,
  s.Q9_confidence, s.Q10_secondary_students, s.Q11D_header, s.Q11A_program_inc_student,
  s.Q11C_support_students_raining_after_school, s.Q11B_encouraging_students_choosing_careers,
  s.Q12_thin_for_students, s.Q13_big_rom_this_orientation,
  s.Q14_nex_after_this_orientation, s.ques_id, s.ques_uuid, s.ques_submission_time,
  s.ques_school_nagaland, s.ques_school_goa, s.ques_school_rajasthan,
  s.ques_school_mumbai, s.ques_school_thane, s.ques_school_pune,
  s.ques_school_osmanabad, s.ques_school_yamunanagar, s.Q17_materials_that_apply,
case when pre_how_did_you_hear like '%newspapers%' then 1 else 0 end as Q7a_newspapers,
case when pre_how_did_you_hear like '%from_government_meetings___oth%' then 1 else 0 end as Q7c_pre_from_government_meetings___oth,
case when pre_how_did_you_hear like '%social_media__facebook__linked%' then 1 else 0 end as Q7b_pre_social_media__facebook__linked,
case when pre_how_did_you_hear like '%from_parents__students%' then 1 else 0 end as Q7d_pre_from_parents__students,
case when pre_how_did_you_hear like '%search_engines___google_etc%' then 1 else 0 end as Q7e_pre_search_engines___google_etc,
case when pre_how_did_you_hear like '%worked_with_them_in_the_past%' then 1 else 0 end as Q7f_pre_worked_with_them_in_the_past,
case when pre_how_did_you_hear like '%workshops__training_sessions__%' then 1 else 0 end as Q7g_pre_workshops__training_sessions__,
case when pre_how_did_you_hear like '%other__please_specify%' then 1 else 0 end as Q7h_pre_other__please_specify,
case when pre_how_did_you_hear like '%not_applicable%' then 1 else 0 end as Q7i_pre_NA,

case when Q8_which_grade like '%grade_8%' then 1 else 0 end as Q8a_pre_grade_8,
case when Q8_which_grade like '%grade_9%' then 1 else 0 end as Q8b_pre_grade_9,
case when Q8_which_grade like '%grade_10%' then 1 else 0 end as Q8c_pre_grade_10,
case when Q8_which_grade like '%grade_11%' then 1 else 0 end as Q8d_pre_grade_11,
case when Q8_which_grade like '%grade_12%' then 1 else 0 end as Q8e_pre_grade_12,
case when Q8_which_grade like '%none_of_the_abovei_don_t_know__not_sure%' then 1 else 0 end as Q8f_pre_none_of_the_above,
case when Q8_which_grade like '%i_don_t_know__not_sure%' then 1 else 0 end as Q8g_pre_i_don_t_know__not_sure,
case when Q8_which_grade like '%other__please_specify%' then 1 else 0 end as Q8h_pre_other__please_specify,

case when Q9_which_follow like '%up__to__date_information_about_careers%' then 1 else 0 end as Q9a_pre_up__to__date_information_about_careers,
case when Q9_which_follow like '%parents__caregivers_sessions%' then 1 else 0 end as Q9b_pre_parents__caregivers_sessions,
case when Q9_which_follow like '%a_trained_career_teacher_in_school%' then 1 else 0 end as Q9c_pre_a_trained_career_teacher_in_school,
case when Q9_which_follow like '%records_of_students_career_plans%' then 1 else 0 end as Q9f_pre_records_of_students_career_plans,
case when Q9_which_follow like '%individual_counselling%' then 1 else 0 end as Q9d_pre_individual_counselling,
case when Q9_which_follow like '%psychometric_tests%' then 1 else 0 end as Q9e_pre_psychometric_tests,
case when Q9_which_follow like '%academic_subjects_teaching_careers%' then 1 else 0 end as Q9g_pre_academic_subjects_teaching_careers,
case when Q9_which_follow like '%information_on_education___training_path%' then 1 else 0 end as Q9h_pre_information_on_education___training_path,
case when Q9_which_follow like '%visits__talks_with_educational_instituti%' then 1 else 0 end as Q9i_pre_visits__talks_with_educational_instituti,
case when Q9_which_follow like '%records_of_student_learning_in_the_caree%' then 1 else 0 end as Q9j_pre_records_of_student_learning_in_the_caree,
case when Q9_which_follow like '%records_of_students_career_plans_after_c%' then 1 else 0 end as Q9k_pre_records_of_students_career_plans_after_c,
case when Q9_which_follow like '%i_don_t_know__not_sure%' then 1 else 0 end as Q9l_pre_i_don_t_know__not_sure,

case when Q10_which_follow like '%i_had_no_role_to_play_in_the_program%' then 1 else 0 end as Q10a_pre_i_had_no_role_to_play_in_the_program,
case when Q10_which_follow like '%provided_a_fixed_time_for_the_career_ses%' then 1 else 0 end as Q10b_pre_provided_a_fixed_time_for_the_career_ses,
case when Q10_which_follow like '%observe_career_sessions_regularly%' then 1 else 0 end as Q10c_pre_observe_career_sessions_regularly,
case when Q10_which_follow like '%ensured_students_attended_the_career_pro%' then 1 else 0 end as Q10d_pre_ensured_students_attended_the_career_pro,
case when Q10_which_follow like '%spoke_to_parents_about_the_career_progra%' then 1 else 0 end as Q10e_pre_spoke_to_parents_about_the_career_progra,
case when Q10_which_follow like '%shared_about_the_career_program_in_hm_me%' then 1 else 0 end as Q10f_pre_shared_about_the_career_program_in_hm_me,
case when Q10_which_follow like '%provided_feedback__suggestions_for_the_p%' then 1 else 0 end as Q10g_pre_provided_feedback__suggestions_for_the_p,
case when Q10_which_follow like '%provided_school_budget__money_for_the_ca%' then 1 else 0 end as Q10h_pre_provided_school_budget__money_for_the_ca,
case when Q10_which_follow like '%regularly_spoke_to_the_career_teacher_ab%' then 1 else 0 end as Q10i_pre_regularly_spoke_to_the_career_teacher_ab,
case when Q10_which_follow like '%ensured_the_program_started_and_ended_on%' then 1 else 0 end as Q10j_pre_ensured_the_program_started_and_ended_on,
case when Q10_which_follow like '%spoke_to_my_school_alumni_to_see_how_the%' then 1 else 0 end as Q10k_pre_spoke_to_my_school_alumni_to_see_how_the,
case when Q10_which_follow like '%ensured_there_is_a_trained_career_teache%' then 1 else 0 end as Q10l_pre_ensured_there_is_a_trained_career_teache,
case when Q10_which_follow like '%i_do_not_know__not_sure%' then 1 else 0 end as Q10m_pre_i_do_not_know__not_sure,

case when Q5_grade like '%grade_8%' then 1 else 0 end as Q5a_ques_grade_8,
case when Q5_grade like '%grade_9%' then 1 else 0 end as Q5b_ques_grade_9,
case when Q5_grade like '%grade_10%' then 1 else 0 end as Q5c_ques_grade_10,
case when Q5_grade like '%grade_11%' then 1 else 0 end as Q5d_ques_grade_11,
case when Q5_grade like '%grade_12%' then 1 else 0 end as Q5e_ques_grade_12,
case when Q5_grade like '%none_of_the_above%' then 1 else 0 end as Q5f_ques_none_of_the_above,
case when Q5_grade like '%i_don_t_know__not_sure%' then 1 else 0 end as Q5g_ques_i_don_t_know__not_sure,
case when Q5_grade like '%other__please_specify%' then 1 else 0 end as Q5h_ques_other__please_specify,

case when Q6_which_follow like '%i_had_no_role_to_play_in_the_program%' then 1 else 0 end as Q6a_ques_i_had_no_role_to_play_in_the_program,
case when Q6_which_follow like '%provided_a_fixed_time_for_the_career_ses%' then 1 else 0 end as Q6b_ques_provided_a_fixed_time_for_the_career_ses,
case when Q6_which_follow like '%observe_career_sessions_regularly%' then 1 else 0 end as Q6c_ques_observe_career_sessions_regularly,
case when Q6_which_follow like '%ensured_students_attended_the_career_pro%' then 1 else 0 end as Q6d_ques_ensured_students_attended_the_career_pro,
case when Q6_which_follow like '%spoke_to_parents_about_the_career_progra%' then 1 else 0 end as Q6e_ques_spoke_to_parents_about_the_career_progra,
case when Q6_which_follow like '%shared_about_the_career_program_in_hm_me%' then 1 else 0 end as Q6f_ques_shared_about_the_career_program_in_hm_me,
case when Q6_which_follow like '%provided_feedback__suggestions_for_the_p%' then 1 else 0 end as Q6g_ques_provided_feedback__suggestions_for_the_p,
case when Q6_which_follow like '%provided_school_budget__money_for_the_ca%' then 1 else 0 end as Q6h_ques_provided_school_budget__money_for_the_ca,
case when Q6_which_follow like '%regularly_spoke_to_the_career_teacher_ab%' then 1 else 0 end as Q6i_ques_regularly_spoke_to_the_career_teacher_ab,
case when Q6_which_follow like '%ensured_the_program_started_and_ended_on%' then 1 else 0 end as Q6j_ques_ensured_the_program_started_and_ended_on,
case when Q6_which_follow like '%arranged_additional_career_activities_in%' then 1 else 0 end as Q6k_ques_arranged_additional_career_activities_in,
case when Q6_which_follow like '%spoke_to_my_school_alumni_to_see_how_the%' then 1 else 0 end as Q6l_ques_spoke_to_my_school_alumni_to_see_how_the,
case when Q6_which_follow like '%ensured_there_is_a_trained_career_teache%' then 1 else 0 end as Q6m_ques_ensured_there_is_a_trained_career_teache,
case when Q6_which_follow like '%i_do_not_know__not_sure%' then 1 else 0 end as Q6n_ques_i_do_not_know__not_sure,

case when Q7_role like '%i_have_no_role_to_play%' then 1 else 0 end as Q7a_ques_i_have_no_role_to_play,
case when Q7_role like '%provide_a_fixed_time_for_the_career_sess%' then 1 else 0 end as Q7b_ques_provide_a_fixed_time_for_the_career_sess,
case when Q7_role like '%observe_career_sessions_regularly%' then 1 else 0 end as Q7c_ques_observe_career_sessions_regularly,
case when Q7_role like '%speak_to_parents_about_the_career_progra%' then 1 else 0 end as Q7d_ques_speak_to_parents_about_the_career_progra,
case when Q7_role like '%ensure_students_attended_the_career_prog%' then 1 else 0 end as Q7e_ques_ensure_students_attended_the_career_prog,
case when Q7_role like '%share_about_the_career_program_in_hm_mee%' then 1 else 0 end as Q7f_ques_share_about_the_career_program_in_hm_mee,
case when Q7_role like '%provide_feedback__suggestions_for_the_pr%' then 1 else 0 end as Q7g_ques_provide_feedback__suggestions_for_the_pr,
case when Q7_role like '%provide_school_budget__money_for_the_car%' then 1 else 0 end as Q7h_ques_provide_school_budget__money_for_the_car,
case when Q7_role like '%regularly_speak_to_the_career_teacher_ab%' then 1 else 0 end as Q7i_ques_regularly_speak_to_the_career_teacher_ab,
case when Q7_role like '%ensuredthe_program_starts_and_ends_on_ti%' then 1 else 0 end as Q7j_ques_ensuredthe_program_starts_and_ends_on_ti,
case when Q7_role like '%arrange_additional_career_activities_in_%' then 1 else 0 end as Q7k_ques_arrange_additional_career_activities_in_,
case when Q7_role like '%speak_to_my_school_alumni_to_see_how_the%' then 1 else 0 end as Q7l_ques_speak_to_my_school_alumni_to_see_how_the,
case when Q7_role like '%ensure_there_is_a_trained_career_teacher%' then 1 else 0 end as Q7m_ques_ensure_there_is_a_trained_career_teacher,
case when Q7_role like '%i_do_not_know__not_sure%' then 1 else 0 end as Q7n_ques_i_do_not_know__not_sure,

case when Q8_materials like '%a_student_book%' then 1 else 0 end as Q8a_ques_a_student_book,
case when Q8_materials like '%a_teacher_guide%' then 1 else 0 end as Q8b_ques_a_teacher_guide,
case when Q8_materials like '%school_poster%' then 1 else 0 end as Q8c_ques_school_poster,
case when Q8_materials like '%career_chatbot%' then 1 else 0 end as Q8d_ques_career_chatbot,
case when Q8_materials like '%student_certificates%' then 1 else 0 end as Q8e_ques_student_certificates,
case when Q8_materials like '%student_assessments%' then 1 else 0 end as Q8f_ques_student_assessments,
case when Q8_materials like '%career_videos%' then 1 else 0 end as Q8g_ques_career_videos,
case when Q8_materials like '%parent_handouts%' then 1 else 0 end as Q8h_ques_parent_handouts,
case when Q8_materials like '%counselling_report%' then 1 else 0 end as Q8i_ques_counselling_report,

case when post_how_did_you_hear like '%Newspaper%' then 1 else 0 end as Q7a_post_Newspaper,
case when post_how_did_you_hear like '%Social_media_(Facebook,_LinkedIn,_Instagram,_etc.)%' then 1 else 0 end as Q7b_post_Social_media_Facebook_linkedin,
case when post_how_did_you_hear like '%From_government_meetings__other%' then 1 else 0 end as Q7c_post_From_government_meetings__other,
case when post_how_did_you_hear like '%From_Parents_Students%' then 1 else 0 end as Q7d_post_From_Parents_Students,
case when post_how_did_you_hear like '%Search_Engines_(_Google,etc)%' then 1 else 0 end as Q7e_post_Search_Engines__Google_etc,
case when post_how_did_you_hear like '%Peer_HMsTeachers%' then 1 else 0 end as Q7f_post_Peer_HMsTeachers,
case when post_how_did_you_hear like '%Conducted_career_education_program_in_my_school%' then 1 else 0 end as Q7g_post_Conducted_career_education_program_in_my_school,
case when post_how_did_you_hear like '%Workshops,_training_sessions,_or_webinars%' then 1 else 0 end as Q7h_post_Workshops_training_sessions_or_webinars,
case when post_how_did_you_hear like '%Word_of_mouth_from_alumni_or_beneficiaries%' then 1 else 0 end as Q7i_post_Word_of_mouth_from_alumni_or_beneficiaries,
case when post_how_did_you_hear like '%Antarangs_website%' then 1 else 0 end as Q7j_post_Antarangs_website,
case when post_how_did_you_hear like '%other__please_specify%' then 1 else 0 end as Q7k_post_other__please_specify,

case when Q8_in_which_grade like '%grade_8%' then 1 else 0 end as Q8a_post_grade_8,
case when Q8_in_which_grade like '%grade_9%' then 1 else 0 end as Q8b_post_grade_9,
case when Q8_in_which_grade like '%grade_10%' then 1 else 0 end as Q8c_post_grade_10,
case when Q8_in_which_grade like '%grade_11%' then 1 else 0 end as Q8d_post_grade_11,
case when Q8_in_which_grade like '%grade_12%' then 1 else 0 end as Q8e_post_grade_12,
case when Q8_in_which_grade like '%none_of_the_above%' then 1 else 0 end as Q8f_post_none_of_the_above,
case when Q8_in_which_grade like '%i_don_t_know__not_sure%' then 1 else 0 end as Q8g_post_i_don_t_know__not_sure,
case when Q8_in_which_grade like '%other__please_specify%' then 1 else 0 end as Q8h_post_other__please_specify,

case when Q9_which_of_the_following like '%Up-to-date_info_about_careers%' then 1 else 0 end as Q9a_post_Up_to_date_info_about_careers,
case when Q9_which_of_the_following like '%Sessions_for_parents_or_caregivers%' then 1 else 0 end as Q9b_post_Sessions_for_parents_or_caregivers,
case when Q9_which_of_the_following like '%Trained_external_career_teacher_at_school%' then 1 else 0 end as Q9c_post_Trained_external_career_teacher_at_school,
case when Q9_which_of_the_following like '%Trained_career_teacher_in_charge%' then 1 else 0 end as Q9d_post_Trained_career_teacher_in_charge,
case when Q9_which_of_the_following like '%One-on-one_career_counselling%' then 1 else 0 end as Q9e_post_One_on_one_career_counselling,
case when Q9_which_of_the_following like '%Interest_and_aptitude_tests%' then 1 else 0 end as Q9f_post_Interest_and_aptitude_tests,
case when Q9_which_of_the_following like '%Record_of_students_career_plans%' then 1 else 0 end as Q9g_post_Record_of_students_career_plans,
case when Q9_which_of_the_following like '%Info_on_education_or_training_after_school%' then 1 else 0 end as Q9h_post_Info_on_education_or_training_after_school,
case when Q9_which_of_the_following like '%Career_expert_talks_during_subject_classes%' then 1 else 0 end as Q9i_post_Career_expert_talks_during_subject_classes,
case when Q9_which_of_the_following like '%Talks_or_visits_to_colleges_and_workplaces%' then 1 else 0 end as Q9j_post_Talks_or_visits_to_colleges_and_workplaces,
case when Q9_which_of_the_following like '%Data_collected_on_students_plans_after_school%' then 1 else 0 end as Q9k_post_Data_collected_on_students_plans_after_school,
case when Q9_which_of_the_following like '%i_do_not_know__not_sure%' then 1 else 0 end as Q9l_post_i_do_not_know__not_sure,

case when Q10_answer_that_apply like '%Fixed_a_regular_time_for_career_sessions%' then 1 else 0 end as Q10a_post_Fixed_a_regular_time_for_career_sessions,
case when Q10_answer_that_apply like '%Visited_the_career_sessions%' then 1 else 0 end as Q10b_post_Visited_the_career_sessions,
case when Q10_answer_that_apply like '%Made_sure_students_attended%' then 1 else 0 end as Q10c_post_Made_sure_students_attended,
case when Q10_answer_that_apply like '%Spoke_to_parents_about_it%' then 1 else 0 end as Q10d_post_Spoke_to_parents_about_it,
case when Q10_answer_that_apply like '%Shared_updates_in_meetings%' then 1 else 0 end as Q10e_post_Shared_updates_in_meetings,
case when Q10_answer_that_apply like '%Shared_updates_in_meetings_or_reports%' then 1 else 0 end as Q10f_post_Shared_updates_in_meetings_or_reports,
case when Q10_answer_that_apply like '%Utilised_school_funds_for_the_program%' then 1 else 0 end as Q10g_post_Utilised_school_funds_for_the_program,
case when Q10_answer_that_apply like '%Talked_often_with_the_career_teacher%' then 1 else 0 end as Q10h_post_Talked_often_with_the_career_teacher,
case when Q10_answer_that_apply like '%Started_and_ended_the_program_on_time%' then 1 else 0 end as Q10i_post_Started_and_ended_the_program_on_time,
case when Q10_answer_that_apply like '%Arranged_extra_career_activities%' then 1 else 0 end as Q10j_post_Arranged_extra_career_activities,
case when Q10_answer_that_apply like '%invited_ex-students_to_share_their_job_stories%' then 1 else 0 end as Q10k_post_invited_ex_students_to_share_their_job_stories,
case when Q10_answer_that_apply like '%Fixed_a_regular_time_for_career_sessions%' then 1 else 0 end as Q10l_post_Fixed_a_regular_time_for_career_sessions,
case when Q10_answer_that_apply like '%i_do_not_know__not_sure%' then 1 else 0 end as Q10m_post_i_do_not_know__not_sure,

case when Q17_materials_that_apply like '%A_student_book%' then 1 else 0 end as Q17a_post_A_student_book,
case when Q17_materials_that_apply like '%A_teacher_guide%' then 1 else 0 end as Q17b_post_A_teacher_guide,
case when Q17_materials_that_apply like '%School_Poster%' then 1 else 0 end as Q17c_post_School_Poster,
case when Q17_materials_that_apply like '%Career_Chatbot%' then 1 else 0 end as Q17d_post_Career_Chatbot,
case when Q17_materials_that_apply like '%Student_Certificates%' then 1 else 0 end as Q17e_post_Student_Certificates,
case when Q17_materials_that_apply like '%Student_Assessments%' then 1 else 0 end as Q17f_post_Student_Assessments,
case when Q17_materials_that_apply like '%Career_Videos%' then 1 else 0 end as Q17g_post_Career_Videos,
case when Q17_materials_that_apply like '%Parent_Handouts%' then 1 else 0 end as Q17h_post_Parent_Handouts,
case when Q17_materials_that_apply like '%Counselling_Report%' then 1 else 0 end as Q17i_post_Counselling_Report

from source_joined s
)

select school_name, hm_session_name, facilitator_name, hm_session_date, start_time, scheduling_type, rescheduled_counter,
session_status, hm_attended, session_lead, session_academic_year, batch_language, school_taluka, school_district,
school_state, school_area, school_partner, pre_start, pre_end, pre_date, pre_name, district_name, school_names, pre_school_nagaland,
pre_school_goa, pre_school_rajasthan, pre_school_mumbai, pre_school_thane, pre_school_pune, pre_school_osmanabad,
pre_school_yamunanagar, pre_contact_number, Q4_years_in_this_school, Q5_organisation_last_year, Q5_option_1, Q5_option_2,
Q5_option_3, Q6_heard_of_antarang, Q7a_newspapers, Q7b_pre_social_media__facebook__linked, Q7c_pre_from_government_meetings___oth,
Q7d_pre_from_parents__students, Q7e_pre_search_engines___google_etc, Q7f_pre_worked_with_them_in_the_past,
Q7g_pre_workshops__training_sessions__, Q7h_pre_other__please_specify, Q7i_pre_NA, Other_Please_Specify, Q8a_pre_grade_8,
Q8b_pre_grade_9, Q8c_pre_grade_10, Q8d_pre_grade_11, Q8e_pre_grade_12,
Q8f_pre_none_of_the_above,
Q8g_pre_i_don_t_know__not_sure,
Q8h_pre_other__please_specify,
Others_Please_Specify,
Q9a_pre_up__to__date_information_about_careers,
Q9b_pre_parents__caregivers_sessions,
Q9c_pre_a_trained_career_teacher_in_school,
Q9d_pre_individual_counselling,
Q9e_pre_psychometric_tests,
Q9f_pre_records_of_students_career_plans,
Q9g_pre_academic_subjects_teaching_careers,
Q9h_pre_information_on_education___training_path,
Q9i_pre_visits__talks_with_educational_instituti,
Q9j_pre_records_of_student_learning_in_the_caree,
Q9k_pre_records_of_students_career_plans_after_c,
Q9l_pre_i_don_t_know__not_sure,
Q10a_pre_i_had_no_role_to_play_in_the_program,
Q10b_pre_provided_a_fixed_time_for_the_career_ses,
Q10c_pre_observe_career_sessions_regularly,
Q10d_pre_ensured_students_attended_the_career_pro,
Q10e_pre_spoke_to_parents_about_the_career_progra,
Q10f_pre_shared_about_the_career_program_in_hm_me,
Q10g_pre_provided_feedback__suggestions_for_the_p,
Q10h_pre_provided_school_budget__money_for_the_ca,
Q10i_pre_regularly_spoke_to_the_career_teacher_ab,
Q10j_pre_ensured_the_program_started_and_ended_on,
Q10k_pre_spoke_to_my_school_alumni_to_see_how_the,
Q10l_pre_ensured_there_is_a_trained_career_teache,
Q10m_pre_i_do_not_know__not_sure,
Q11_think_of_career,
Q12_confident_in_career_program,
pre_program_acitivities,
Q14_program_session,
pre_important_secondary_students,
Q16A_program_inclution_of_all_students,
Q16C_supporting_students_training_after_school,
Q16B__encouraging_students_choosing_careers,
Q17_one_thing_for_you_students,
pre_id,
pre_uuid,
pre_submission_time,
pre_school_name,
ques_start,
ques_end,
ques_date,
ques_name,
ques_school_name,
ques_district_name,
ques_contact_number,
Q4_heard_of_antarang,
Q5a_ques_grade_8,
Q5b_ques_grade_9,
Q5c_ques_grade_10,
Q5d_ques_grade_11,
Q5e_ques_grade_12,
Q5f_ques_none_of_the_above,
Q5g_ques_i_don_t_know__not_sure,
Q5h_ques_other__please_specify,
ques_others_please_specify,
Q6a_ques_i_had_no_role_to_play_in_the_program,
Q6b_ques_provided_a_fixed_time_for_the_career_ses,
Q6c_ques_observe_career_sessions_regularly,
Q6d_ques_ensured_students_attended_the_career_pro,
Q6e_ques_spoke_to_parents_about_the_career_progra,
Q6f_ques_shared_about_the_career_program_in_hm_me,
Q6g_ques_provided_feedback__suggestions_for_the_p,
Q6h_ques_provided_school_budget__money_for_the_ca,
Q6i_ques_regularly_spoke_to_the_career_teacher_ab,
Q6j_ques_ensured_the_program_started_and_ended_on,
Q6k_ques_arranged_additional_career_activities_in,
Q6l_ques_spoke_to_my_school_alumni_to_see_how_the,
Q6m_ques_ensured_there_is_a_trained_career_teache,
Q6n_ques_i_do_not_know__not_sure,
Q7a_ques_i_have_no_role_to_play,
Q7b_ques_provide_a_fixed_time_for_the_career_sess,
Q7c_ques_observe_career_sessions_regularly,
Q7d_ques_speak_to_parents_about_the_career_progra,
Q7e_ques_ensure_students_attended_the_career_prog,
Q7f_ques_share_about_the_career_program_in_hm_mee,
Q7g_ques_provide_feedback__suggestions_for_the_pr,
Q7h_ques_provide_school_budget__money_for_the_car,
Q7i_ques_regularly_speak_to_the_career_teacher_ab,
Q7j_ques_ensuredthe_program_starts_and_ends_on_ti,
Q7k_ques_arrange_additional_career_activities_in_,
Q7l_ques_speak_to_my_school_alumni_to_see_how_the,
Q7m_ques_ensure_there_is_a_trained_career_teacher,
Q7n_ques_i_do_not_know__not_sure,
Q8a_ques_a_student_book,
Q8b_ques_a_teacher_guide,
Q8c_ques_school_poster,
Q8d_ques_career_chatbot,
Q8e_ques_student_certificates,
Q8f_ques_student_assessments,
Q8g_ques_career_videos,
Q8h_ques_parent_handouts,
Q8i_ques_counselling_report,
Q9_confidence,
Q10_secondary_students,
Q11D_header,
Q11A_program_inc_student,
Q11C_support_students_raining_after_school,
Q11B_encouraging_students_choosing_careers,
Q12_thin_for_students,
Q13_big_rom_this_orientation,
Q14_nex_after_this_orientation,
ques_id,
ques_uuid,
ques_submission_time,
post_start,
post_end,
post_date,
post_name,
post_district_name,
post_school_name,
post_contact_number,
Q4_how_many_year_in_this_school,
Q5_org_our_school_last_year,
post_others_please_specify,
Q6_heard_of_antarng,
Q7a_post_Newspaper,
Q7b_post_Social_media_Facebook_linkedin,
Q7c_post_From_government_meetings__other,
Q7d_post_From_Parents_Students,
Q7e_post_Search_Engines__Google_etc,
Q7f_post_Peer_HMsTeachers,
Q7g_post_Conducted_career_education_program_in_my_school,
Q7h_post_Workshops_training_sessions_or_webinars,
Q7i_post_Word_of_mouth_from_alumni_or_beneficiaries,
Q7j_post_Antarangs_website,
Q7k_post_other__please_specify,
Q8a_post_grade_8,
Q8b_post_grade_9,
Q8c_post_grade_10,
Q8d_post_grade_11,
Q8e_post_grade_12,
Q8f_post_none_of_the_above,
Q8g_post_i_don_t_know__not_sure,
Q8h_post_other__please_specify,
Q9a_post_Up_to_date_info_about_careers,
Q9b_post_Sessions_for_parents_or_caregivers,
Q9c_post_Trained_external_career_teacher_at_school,
Q9d_post_Trained_career_teacher_in_charge,
Q9e_post_One_on_one_career_counselling,
Q9f_post_Interest_and_aptitude_tests,
Q9g_post_Record_of_students_career_plans,
Q9h_post_Info_on_education_or_training_after_school,
Q9i_post_Career_expert_talks_during_subject_classes,
Q9j_post_Talks_or_visits_to_colleges_and_workplaces,
Q9k_post_Data_collected_on_students_plans_after_school,
Q9l_post_i_do_not_know__not_sure,
Q10a_post_Fixed_a_regular_time_for_career_sessions,
Q10b_post_Visited_the_career_sessions,
Q10c_post_Made_sure_students_attended,
Q10d_post_Spoke_to_parents_about_it,
Q10e_post_Shared_updates_in_meetings,
Q10f_post_Shared_updates_in_meetings_or_reports,
Q10g_post_Utilised_school_funds_for_the_program,
Q10h_post_Talked_often_with_the_career_teacher,
Q10i_post_Started_and_ended_the_program_on_time,
Q10j_post_Arranged_extra_career_activities,
Q10k_post_invited_ex_students_to_share_their_job_stories,
Q10l_post_Fixed_a_regular_time_for_career_sessions,
Q10m_post_i_do_not_know__not_sure,
Q11_thin_for_career_program,
Q12_confident,
post_program_activities,
Q14_program_sessions,
post_important_secondary_students,
Q16_career_decisions,
Q17_materials_that_apply,
Q17a_post_A_student_book,
Q17b_post_A_teacher_guide,
Q17c_post_School_Poster,
Q17d_post_Career_Chatbot,
Q17e_post_Student_Certificates,
Q17f_post_Student_Assessments,
Q17g_post_Career_Videos,
Q17h_post_Parent_Handouts,
Q17i_post_Counselling_Report,
Q18D_header,
Q18A_program_inc_of_all_students,
Q18C_supporting_students_raining_after_school,
Q18B_encouraging_students_choosing_careers,
Q19_leave_school,
Q20_thin_for_students,
post_uuid,
post_submission_time
from expand_column