select student_name, first_barcode, student_barcode, gender, current_barcode, current_batch_no, birth_year, birth_date, g9_whatsapp_no, 
g10_whatsapp_no, g11_whatsapp_no, g12_whatsapp_no, religion, 
caste, father_education, father_occupation, mother_education, mother_occupation, student_details_2_submitted, batch_id, batch_no, 
batch_academic_year, batch_grade, batch_language, no_of_students_facilitated, fac_start_date, fac_end_date, facilitator_name, facilitator_email, 
school_name, school_taluka, school_ward, school_district, school_state, enrolled_g9, enrolled_g10, enrolled_g11, enrolled_g12, 
tagged_for_counselling, school_partner, school_area, batch_donor, session_id, session_code, session_name, session_type, session_date, 
session_no, omr_required, omrs_received, total_student_present, total_parent_present, log_reason, attendance_submitted, present_count, 
attendance_count, payment_status, parent_present_count, session_mode, batch_expected_sessions, batch_expected_student_type_session, 
batch_expected_parent_type_session, batch_expected_flexible_type_session, batch_expected_counseling_type_session, batch_scheduled_sessions, 
batch_student_type_scheduled_sessions, batch_parent_type_scheduled_sessions, batch_flexible_type_scheduled_sessions, 
batch_counseling_type_scheduled_sessions, batch_completed_sessions, batch_student_type_completed_sessions, batch_parent_type_completed_sessions, 
batch_flexible_type_completed_sessions, batch_Counseling_type_completed_sessions, batch_max_student_session_attendance, 
batch_max_session_parent_attendance, batch_max_session_flexible_attendance, batch_max_session_counseling_attendance, batch_indi_stud_attendance, 
batch_indi_parent_attendance, batch_indi_flexible_attendance, batch_indi_counseling_attendance, batch_max_overall_attendance, 
total_reached_parents from {{ref('dev_int_global_session')}}
where batch_academic_year >= 2023